import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { SiteHeader } from '@/components/landing/site-header'
import { SiteFooter } from '@/components/landing/site-footer'
import { Button } from '@/components/ui/button'

const sections = [
  {
    index: '01',
    title: 'Build a persona',
    body: 'Go to Persona Builder to create a consumer profile — age, income, wealth, debt, education, and preferences like risk appetite and spending behavior. These fields directly drive the simulation math.',
  },
  {
    index: '02',
    title: 'Configure a scenario',
    body: 'In Scenarios, pick one of the 8 preset macroeconomic conditions (inflation, interest rates, unemployment, market confidence, and more) or fine-tune your own with the sliders.',
  },
  {
    index: '03',
    title: 'Run a simulation',
    body: 'From the Dashboard, select a persona and scenario and hit Run Simulation. Results show projected spending, saving, borrowing, and investing decisions with confidence scores.',
  },
  {
    index: '04',
    title: 'Review Analytics & Reports',
    body: 'Analytics breaks down spending distribution, savings trends, and confidence scores across personas. Reports lets you generate and export summaries as JSON.',
  },
]

export default function DocumentationPage() {
  return (
    <main className="w-full">
      <SiteHeader />
      <div className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-xs font-medium text-primary uppercase tracking-wide mb-2">Documentation</p>
        <h1 className="font-heading text-4xl font-medium mb-4 tracking-tight">Getting started</h1>
        <p className="text-muted-foreground mb-10">
          EconoMind has four moving parts. Here's how they fit together.
        </p>

        <div className="border-t border-border mb-12">
          {sections.map((s) => (
            <div key={s.title} className="py-6 flex items-start gap-6 border-b border-border">
              <span className="font-heading text-2xl text-primary/60 flex-shrink-0 w-10 tabular-nums">
                {s.index}
              </span>
              <div>
                <h3 className="font-medium mb-1">{s.title}</h3>
                <p className="text-muted-foreground text-sm">{s.body}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="rounded-xl border border-border p-6 mb-10">
          <h2 className="font-heading text-xl font-medium mb-2">What's real vs. illustrative</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The 8 economic scenarios and the demographic math (income, wealth, expenses) are
            defined datasets, consistent everywhere they're used. Simulation decisions and
            behavioral trait scores are generated by a simple illustrative model (base ranges plus
            randomness), not a trained economic model — see{' '}
            <Link href="/methodology" className="text-primary hover:underline">
              Methodology
            </Link>{' '}
            for details. Treat results as directional, not predictive.
          </p>
        </div>

        <Link href="/dashboard">
          <Button className="gap-2">
            Open the dashboard
            <ArrowRight className="w-4 h-4" />
          </Button>
        </Link>
      </div>
      <SiteFooter />
    </main>
  )
}
